FROM python:3.9-slim

WORKDIR /app

COPY data_crawler/requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY ./data_crawler ./data_crawler

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "data_crawler.data_crawler:app", "--host", "0.0.0.0", "--port", "8081"]
