FROM python:3.9-slim

WORKDIR /app

COPY api/requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY ./api ./api

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]
