FROM python:3.10-slim

WORKDIR /app

COPY crawlers/soil/soil_crawler.py ./crawlers/soil/soil_crawler.py
COPY configs/requirements.txt ./requirements.txt
COPY configs/.env ./configs/.env

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8083

CMD ["uvicorn", "crawlers.soil.soil_crawler:app", "--host", "0.0.0.0", "--port", "8083"]
