FROM python:3.9-slim

WORKDIR /app

COPY ../configs/requirements_crawler.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ../crawlers/water/water_crawler.py ./crawlers/water/
COPY ../configs/.env.example ./configs/.env.example

EXPOSE 8082

CMD ["uvicorn", "crawlers.water.water_crawler:app", "--host", "0.0.0.0", "--port", "8082"]