FROM python:3.9-slim

WORKDIR /app

COPY ../configs/requirements_crawler.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ../crawlers/climate/climate_crawler.py ./crawlers/climate/
COPY ../configs/.env.example ./configs/.env.example

EXPOSE 8084

CMD ["uvicorn", "crawlers.climate.climate_crawler:app", "--host", "0.0.0.0", "--port", "8084"]