FROM python:3.10-slim

WORKDIR /app

COPY crawlers/water/water_crawler.py ./crawlers/water/water_crawler.py
COPY configs/requirements.txt ./requirements.txt
COPY configs/.env ./configs/.env

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8082

CMD ["uvicorn", "crawlers.water.water_crawler:app", "--host", "0.0.0.0", "--port", "8082"]
