FROM python:3.9-slim

WORKDIR /app

COPY data_cleaner/requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY ./data_cleaner ./data_cleaner

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "data_cleaner.clean_data:app", "--host", "0.0.0.0", "--port", "8080"]
