FROM python:3.10-slim

WORKDIR /app

COPY api/ ./api/
COPY configs/requirements.txt ./requirements.txt
COPY configs/.env ./configs/.env

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]
