FROM python:3.10-slim

WORKDIR /app

COPY crawlers/climate/climate_crawler.py ./crawlers/climate/climate_crawler.py
COPY configs/requirements.txt ./requirements.txt
COPY configs/.env ./configs/.env

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8084

CMD ["uvicorn", "crawlers.climate.climate_crawler:app", "--host", "0.0.0.0", "--port", "8084"]
