# Sử dụng python:3.9-slim để giảm kích thước image
FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && \
    pip install -r configs/requirements.txt && \
    pip install python-multipart

EXPOSE 8090

CMD ["uvicorn", "Cleaners.main_cleaner:app", "--host", "0.0.0.0", "--port", "8090"]
# hoặc nếu chỉ muốn chạy batch:
# CMD ["python", "-m", "Cleaners.air_cleaner"]