FROM python:3.9-slim

WORKDIR /app

COPY ../configs/requirements_soil.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ../crawlers/soil/soil_crawler.py ./crawlers/soil/
COPY ../configs/.env.example ./configs/.env.example

EXPOSE 8083

CMD ["uvicorn", "crawlers.soil.soil_crawler:app", "--host", "0.0.0.0", "--port", "8083"]